### ISSUE TITLE
add support AR?

### ISSUE THREAD

**Issue by omagadsamsa** [touchHLE/touchHLE#209]
in some games on the easy studio engine (which have a 1-2 second intro included in the game with a black engine logo) there are AR games and, in general, some games also need this function like ARwar (easy studio engine)

**Comment by hikari-no-yume** [comment]
Uhh. Are there any games for iPhone OS 2 or iPhone OS 3 that support this?

**Comment by omagadsamsa** [comment]
yes, I can send you the list

**Comment by omagadsamsa** [comment]
> Uhh. Are there any games for iPhone OS 2 or iPhone OS 3 that support this?

yes, I can send you the list

**Comment by omagadsamsa** [comment]
> games:ARwar(iphoneos 2
Also, maybe in a hacker simulator that doesn’t let you in from the eyes, but the fingerprints work. Its iphoneos 3 game

**Comment by hikari-no-yume** [comment]
Do any of these games actually run in touchHLE right now?

**Comment by omagadsamsa** [comment]
about Capsel Racer only on the phone, but now I’ll check the rest of the games on the phone and PC

**Comment by ciciplusplus** [comment]
What does AR even mean here?

For Augmented Reality, I don't think early iOS have any build-in support or any exposed API.
