### ISSUE TITLE
rayman 2 free artifacte bug

### ISSUE THREAD

**Issue by omagadsamsa** [touchHLE/touchHLE#252]
huawei y6 
![image](https://github.com/hikari-no-yume/touchHLE/assets/149837198/29d6c4bb-71ba-406e-8a10-10e935f1b95b)

**Comment by omagadsamsa** [comment]
> omagadsamsa

![image](https://github.com/hikari-no-yume/touchHLE/assets/149837198/0291ac0f-aa08-41d7-b2c8-fb9391098806)

**Comment by omagadsamsa** [comment]
in meizu m6 normal work

**Comment by omagadsamsa** [comment]
its bug and in castle of magic, zombie mansion

**Comment by hikari-no-yume** [comment]
Ah, this is a PowerVR GPU phone.

**Comment by hikari-no-yume** [comment]
I meant the Huawei Y6.

**Comment by omagadsamsa** [comment]
> I meant the Huawei Y6.

Huawei y6 2018 🤧, no 2019 and more

**Comment by omagadsamsa** [comment]
![Screenshot_20240403-175249](https://github.com/touchHLE/touchHLE/assets/149837198/5e08c162-a94f-4c7e-a61e-2896cf689151)

**Comment by omagadsamsa** [comment]
https://youtu.be/aDW9JcZyY4U?si=BJGam41yOs7BW0OU

**Comment by hikari-no-yume** [comment]
I see, thanks for the information.

**Comment by omagadsamsa** [comment]
no artifacts in actual build
