### ISSUE TITLE
Add compatibility

### ISSUE THREAD

**Issue by WinUser-Generic** [touchHLE/touchHLE#264]
Is possible to add compatibility with world at war zombies? Latest version (iOS 3) It just open and close inmediatelly trying to load ipa file. I wish too in future can be compatible with hd versión (iOS 3.2) and with black ops zombies (iOS 5) to can enjoy complete saga emulated. Here a paste of log, but first my specs:
Xiaomi 13T
Android 14
8gb ram + 8gb virtual
CPU Mediatek dimensity 8200 ultra
Gpu Mali G610 Mc6

Log paste:
touchHLE v0.2.1 — https://touchhle.org/

touchHLE: Base path for touchHLE files: /storage/emulated/0/Android/data/org.touchhle.android/files
No app specified, opening app picker. Use the --help flag to see command-line usage.
touchHLE::window: Accelerometer detected: lsm6dsoq_acc.
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL ES-CM 1.1 v1.r32p1-01eac0.54329dee8f160f288c574caaf67bbe3f / ARM / Mali-G610 MC6
touchHLE::frameworks::uikit::ui_touch: Couldn't find a view for touch at CGPoint { x: 47.104256, y: 580.7738 } in window 0x3550, discarding
touchHLE::frameworks::uikit::ui_touch: Couldn't find a view for touch at CGPoint { x: 72.9644, y: 555.72565 } in window 0x3550, discarding
touchHLE::frameworks::uikit::ui_touch: Couldn't find a view for touch at CGPoint { x: 231.56146, y: -102.19108 } in window 0x3550, discarding
touchHLE::window: Received app-will-resign-active event.
touchHLE::frameworks::uikit: Handling app-will-resign-active event: exiting.

**Comment by hikari-no-yume** [comment]
We do not take requests, sorry. Please read the text before opening an issue.

**Comment by WinUser-Generic** [comment]
Rewally you take like a request? this app has compatibility with iOS 3 and waw zombies is iOS 3 app, lol also i provided the log, and the opther was just a suggestion... i like when devs are than rude ok.

**Comment by WinUser-Generic** [comment]
And please point to anything, not just link nothing.
![image](https://github.com/touchHLE/touchHLE/assets/159548162/3fa43f27-d8f4-4fda-aae8-675e6e8417e5)

**Comment by hikari-no-yume** [comment]
I don't see how my response was rude. I was direct but I didn't insult you, and I even was kind enough to say “sorry”. For what it's worth, it might be considered rude of you to not read the guidelines before submitting an issue. I don't think I need to link to them, they will have appeared when you clicked the ”New issue” button:

![image of the text that appears when you click “New issue”](https://github.com/touchHLE/touchHLE/assets/579774/81454f30-8b1a-45d1-86ec-071de91c1659)

**Comment by hikari-no-yume** [comment]
The important part is “please don't open issues about broken apps”.
