### ISSUE TITLE
save no work eathworm jim

### ISSUE THREAD

**Issue by omagadsamsa** [touchHLE/touchHLE#266]
i complete two boss and i close game. i on game and save nothing

**Comment by ciciplusplus** [comment]
On the level select menu, can you select other levels apart from the first one?

**Comment by omagadsamsa** [comment]
select no works

**Comment by omagadsamsa** [comment]
https://youtu.be/099kCl4PJ54?si=NrN_m2i-zsFwrbEM select hard work

**Comment by ciciplusplus** [comment]
It is the same issue as you reported here https://github.com/touchHLE/touchHLE/issues/265
Saving mechanism itself is working as expected
