### ISSUE TITLE
Wolfenstein 3D: when you open the console (4 fingers to the top the game crashes)

### ISSUE THREAD

**Issue by omagadsamsa** [touchHLE/touchHLE#284]
game version 1.3, huawei y6 2018

**Comment by omagadsamsa** [comment]
in doom work

**Comment by ciciplusplus** [comment]
Please provide a crash log.

**Comment by omagadsamsa** [comment]
touchHLE v0.2.2-27-ga4fcf0d — https://touchhle.org/

touchHLE: Base path for touchHLE files: /storage/emulated/0/Android/data/org.touchhle.android/files
No app specified, opening app picker. Use the --help flag to see command-line usage.
touchHLE::window: Accelerometer detected: BMA255 Accelerometer/Temperature/Double-tap.
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 308
Picked: /storage/emulated/0/Android/data/org.touchhle.android/files/touchHLE_apps/wolf3d__1.3.ipa
App bundle info:
- Display name: wolf3d+
- Version: 1.3
- Identifier: com.idsoftware.wolf3d
- Internal name (canonical): wolf3d.app
- Minimum OS version: 2.0

Using options from touchHLE_default_options.txt for this app: --landscape-right
No options found for this app in /storage/emulated/0/Android/data/org.touchhle.android/files/touchHLE_options.txt

touchHLE::window: Accelerometer detected: BMA255 Accelerometer/Temperature/Double-tap.
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 308
touchHLE::mach_o: Loading armv6 slice for "wolf3d"
touchHLE::mach_o: Loading armv6 slice for "libgcc_s.1.dylib"
CPU emulation begins now.
touchHLE::frameworks::uikit::ui_nib: TODO: UIProxyObject replacement for IBFirstResponder, instance 0x3000c250 left unreplaced
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::frameworks::opengles::eagl: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 308
touchHLE::window: This app uses the accelerometer.
touchHLE::window: Your device's accelerometer will be used for accelerometer simulation.
touchHLE::window: Connect a controller if you would prefer to use an analog stick.
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::frameworks::opengles::gles_guest: Warning: glGetError() returned 0x501
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::errno: TODO: errno accessed on thread 0 (will always be 0)
touchHLE::window: This app uses the accelerometer.
touchHLE::window: Your device's accelerometer will be used for accelerometer simulation.
touchHLE::window: Connect a controller if you would prefer to use an analog stick.
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::frameworks::uikit::ui_touch: Couldn't find a view for touch at CGPoint { x: 214.93956, y: 481.98834 } in window 0x3000c320, discarding
touchHLE::frameworks::uikit::ui_view::ui_control::ui_text_field: TODO: setAutocapitalizationType:0
touchHLE::frameworks::uikit::ui_view::ui_control::ui_text_field: TODO: setAutocorrectionType:1
Panic at src/mem.rs:337:9: Attempted null-page access at 0x0 (0x1 bytes)
Register state immediately after panic:
	 R0: 0xfffffcc8	 R1: 0x00000000	 R2: 0x0004b268	 R3: 0x3000c430
	 R4: 0x0000003a	 R5: 0x00000159	 R6: 0x00053de1	 R7: 0xfffffde0
	 R8: 0xfffffcc8	 R9: 0x00000000	R10: 0xffffffd8	R11: 0x00000247
	R12: 0x00000000	 SP: 0xfffffcb0	 LR: 0x0000dc74	 PC: 0x0002e3c4
Attempting to produce stack trace for main thread:
 0. 0x2e3c4 (PC)
 1. 0xdc74 (LR)
 2. 0x53c8
 3. 0x2b0e4
 4. [host function]
 5. 0x24b0
Next FP (0x0) is outside the stack.

**Comment by omagadsamsa** [comment]
This is not an application bug, 1.0,1.1,1.2, and 1.3 crash when you open the keyboard

**Comment by ciciplusplus** [comment]
Should be fixed with https://github.com/touchHLE/touchHLE/commit/0f08e9759162ef7bd01ad83d57c3a82cf1c5b989, please check.

**Comment by omagadsamsa** [comment]
> Should be fixed with [0f08e97](https://github.com/touchHLE/touchHLE/commit/0f08e9759162ef7bd01ad83d57c3a82cf1c5b989), please check.

work
