### ISSUE TITLE
create your own explorer in the emulator

### ISSUE THREAD

**Issue by omagadsamsa** [touchHLE/touchHLE#294]
Some people may not be able to transfer files to the emulator folder via adb because they don’t have access to the computer, and they can’t open it through Explorer. ipa file. proposing to create an explorer like in the emulator like in Saturn. emu

**Comment by hikari-no-yume** [comment]
touchHLE already has a Document Provider that makes it visible to Android file managers. Another file manager is not necessary.

**Comment by omagadsamsa** [comment]
> touchHLE already has a Document Provider that makes it visible to Android file managers. Another file manager is not necessary.

I can’t see anything, maybe this is an Android 8 problem?

**Comment by hikari-no-yume** [comment]
It was tested on Android 8. It will show up alongside things like Google Drive and other cloud storage.
