### ISSUE TITLE
fake report Red alert

### ISSUE THREAD

**Issue by omagadsamsa** [touchHLE/touchHLE#305]
game no work. 
![IMG_20240515_050017](https://github.com/touchHLE/touchHLE/assets/149837198/e6f50a1e-4db4-483a-bddb-7ed01a78a339)

**Comment by ciciplusplus** [comment]
@hikari-no-yume do we want to keep track of issues related to user-generated content of appdb here?
I don't think it's relevant to the touchHLE repo itself.

**Comment by thundergun1** [comment]
I saw the iPad version of Worms HD appear on the DB a month or two ago but it was deleted the next day pretty much

**Comment by omagadsamsa** [comment]
> I saw the iPad version of Worms HD appear on the DB a month or two ago but it was deleted the next day pretty much

It's screen in kahvibreak

**Comment by omagadsamsa** [comment]
It seems to me that they are doing this on purpose, perhaps in the future there will be gameplay with a virus apk or exe

**Comment by hikari-no-yume** [comment]
> @hikari-no-yume do we want to keep track of issues related to user-generated content of appdb here?
>
> I don't think it's relevant to the touchHLE repo itself.

This is a good question. For the moment I think it's fine for these issues to go here. I don't have a better place for them.

----

@omagadsamsa I'll look closer, thanks for the report.

**Comment by omagadsamsa** [comment]
look at the sary screenshot of Worms HD in the kahvibreak discord and here is an red alert, maybe it’s the same person

**Comment by omagadsamsa** [comment]
> It's True,Not Fake😒

Feel🤑👹🤡

**Comment by omagadsamsa** [comment]
Game feke no menu gameplay no work ipa by iPad 3.0 no 3.2 version no real

**Comment by thundergun1** [comment]
It could be rated 2 stars by mistake tbf. The lack of a screenshot and description is a lot like most of the 1 star reports on the DB

**Comment by omagadsamsa** [comment]
> It could be rated 2 stars by mistake tbf. The lack of a screenshot and description is a lot like most of the 1 star reports on the DB

There was one request where it supposedly shows that the Worms iPad is working, there is a second star and a bunch of errors and the person does not show that it works or not. the person who made the report: make a video where it starts with at least two stars

**Comment by omagadsamsa** [comment]
can you delete the report? it's just a fake, nothing works from it.

**Comment by hikari-no-yume** [comment]
I tested the app and it would be a 1-star, not a 2-star, as it doesn't get beyond Default.png as far as I can tell. Also, the minimum iOS version and app version fields were wrong. For these reasons, I have deleted the report. But the report was overall clearly in good faith, I don't think it was malicious.
