### ISSUE TITLE
Mini Golf Wacky Worlds

### ISSUE THREAD

**Issue by Justinchong12345** [touchHLE/touchHLE#308]
I remembered this golf game back when I have an iPod Touch. Unfortunately, nobody else remembers this game. So I couldn't find an ipa file for this game (NOTE: DON'T REPLY A LINK TO DOWNLOAD THE IPA FILE BECAUSE OF PIRACY!). If anyone remembers this game, you deserve an award.
![mini-golf-wacky-world-menu](https://github.com/touchHLE/touchHLE/assets/43706809/77fb61d3-2f26-4fe0-bbb7-c5c317894ddd)

**Comment by hikari-no-yume** [comment]
Deleting due to implied reference to piracy.
