### ISSUE TITLE
Iphone 3

### ISSUE THREAD

**Issue by KintCark** [touchHLE/touchHLE#313]
I thought I read something that said touchhle supports ios 3 but I downloaded a 20gb worth of ios 3 games like I wanted to play splinter cell but when I try to open the game the app crashes. So only ios 2 games work?

**Comment by hikari-no-yume** [comment]
> Read this text, but delete it, before posting an issue:
>
> […]
>
> Also, please bear in mind that there are infinitely many apps that do not work in touchHLE right now, so please don't open issues about broken apps unless one of these applies:

The fact that some iPhone OS 3 games work does not mean that all iPhone OS 3 games work.
