### ISSUE TITLE
Tv show king support 

### ISSUE THREAD

**Issue by dskmusic** [touchHLE/touchHLE#343]
### By submitting this issue, I certify that…

- [X] I understand my issue will be immediately rejected.

**Comment by dskmusic** [comment]
Please, add support to this great game. Thanks for the wonderful work!

**Comment by ciciplusplus** [comment]
We do not take game requests.

According to the app db https://appdb.touchhle.org/apps/354, this game already have a 3 star rating with trunk builds.
