### ISSUE TITLE
Archive.org is not working!

### ISSUE THREAD

**Issue by VadymStasiv** [touchHLE/touchHLE#374]
### Describe the feature or issue.

I can't download ios 2.0 games in Archive.org!

### By submitting this issue, I certify that…

- [ ] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [ ] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by ciciplusplus** [comment]
> I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.

banned
